### ISSUE TITLE
(Pre-)Repease tag for LSQ2

### ISSUE THREAD

**Issue by bigerl** [AKSW/LSQ#17]
@Aklakan @saleem-muhammad 
what is the status of LSQ 2? Is the vocabulary finalized?
If it is more or less stable, could you create a tag? That would help us a lot to start using it.
Thx and Best
Alex

**Comment by Aklakan** [comment]
I'd say it's good enough for release; I can make a fresh snapshot today, and a release after the weekend (I have a bit of uncommitted cleanup)

**Comment by Aklakan** [comment]
Meh, things are still a bit complicated but progressing: the lsq code depends on the cli code of [rdf-processing-toolkit (rpt)](https://github.com/SmartDataAnalytics/RdfProcessingToolkit)- but of course i don't want to have to release one (nearly-but-not-totally-release-ready) tool in order to release the other - so i need to disentangle lsq from rpt. Actually, most of the common code has already been moved to [jena-sparql-api](https://github.com/AKSW/jena-sparql-api) over the past months, but the the 'last mile' updates to lsq's code were missing. Shouldn't take longer than at most 1 more day though.

**Comment by Aklakan** [comment]
After dealing with a rat tail of issues, the snapshot is now ready:
Release version will hopefully finish early next week.

```xml
<dependency>
  <groupId>org.aksw.simba.lsq</groupId>
  <artifactId>lsq-vocab-jena</artifactId>
  <version>2.0.0-SNAPSHOT</version>
</dependency>

        <distributionManagement>
                <snapshotRepository>
                        <id>maven.aksw.snapshots</id>
                        <name>AKSW Snapshot Repository</name>
                        <url>http://maven.aksw.org/archiva/repository/snapshots</url>
                </snapshotRepository>
        </distributionManagement>
```

**Comment by bigerl** [comment]
thx a lot :)
